services:
  # A Docker web service
  - type: web
    name: fiber
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    envVars:
      - key: DB_URL
        fromDatabase:
          name: test
          property: connectionString
databases:
  # db 1
  - name: test
    region: frankfurt
    plan: free
    user: gorm
